[package]
name = "bincol"
version = "0.1.0"
edition = "2024"

[dependencies]
bitvec = "1.0.1"
indexmap = { version = "2.12.1", features = ["serde"] }
ron = "0.12.0"
serde = { version = "1.0.228", features = ["derive"] }
thin-vec = "0.2.14"
thiserror = "2.0.17"
